//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinedDBWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoonBadge
    {
        public int Id { get; set; }
        public Nullable<int> Persoon { get; set; }
        public Nullable<int> Badge { get; set; }
    }
}
